[package]
name = "mapannot_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
image = "0.25.2"
log = "0.4.22"
mime_guess = "2.0.5"
slint = "1.7.2"
tiny-skia = "0.11.4"

[build-dependencies]
slint-build = "1.7.2"
